### PR TITLE
Allowing injection of Auth instance for unit testing mocking purposes

### PR DESCRIPTION
**Pull request by firstclown**
Change the instance method to allow an optional object to be passed to set the instance for subsequent requests. Needed to allow use of a mock Auth object in unit tests.

### CODE REVIEW

**Comment by kiall** [comment]
Humm - That should have been considered mergeable... Must be a bug in the pull request tester.

**Comment by firstclown** [comment]
I merged the changes on 3.1/develop back into my branch. Does this help the problem or make it worse?

**Comment by kiall** [comment]
Apologies, Just restored CI server from backup .. Its not quite fixed yet ;) Ignore those last messages!

!build

**Comment by kemo** [comment]
This doesn't really follow Kohana conventions:

```
public static function instance($instance = NULL)
```

and 

```
if ($instance !== NULL)
```

**Pull request closed without merging**
