### PR TITLE
Resolve composer downloading and caching issues on Travis

### PR DESCRIPTION
**Pull request by enov**
Related to kohana/core#650

### CODE REVIEW

**Comment by acoulton** [comment]
Thanks @enov,

I can't immediately see why this one is stubbornly failing on composer install but the other modules are all ok... Any ideas?

**Comment by enov** [comment]
Hmmm, maybe we should resort to [--prefer-source](https://github.com/composer/composer/issues/1314#issuecomment-13497719) but I guess it would be much slower.

**Comment by acoulton** [comment]
OK so I think the reason only the prefer-lowest build was failing was that the others already had correct dist versions in their cache already so `composer install` wasn't actually downloading or installing anything.

Oddly though the downloads for `composer update` were then failing with a `401` - according to the API docs, the rate limiting responses are all `403`. It looks like `composer update` doesn't fall back to source in the same way.

It seems hit and miss though, I cleared the cache and some of the builds failed to authenticate and fell back to clones while others managed to do the downloads.

According to composer/composer#4884 though, the rate limits on downloads have been removed so I'm not sure why this is still intermittently failing.

`--prefer-source` might work (at least for the `--prefer-lowest` build as the others look like they recover OK) but as you say will slow it down and feels like it's bad for everyone compared to just grabbing the archive.

**Comment by acoulton** [comment]
well, clearing the travis caches seems to have removed the issue, I've restarted the build a few times and it's consitently downloading OK. Maybe there was some sort of invalid oauth token or other artifact stuck in there from a previous build / composer version.

**Pull request merged**
