### PR TITLE
Random salts and flexible hash storage for Auth

### PR DESCRIPTION
**Pull request by tylerl**
First of all, even though this patch changes password hashing, **it does not "break" existing hashes**, as the old hash format is detected and honored by the new code. Old 3.1-style password hashes will still work.

This patch fixes bug #[3605](http://dev.kohanaframework.org/issues/3605). That wasn't the goal, but it's a side-effect.

Though the changes in hashing introduced in 3.1 were a step in the right direction, the stored password hashes are _still_ not as secure as they should be. Hashes are salted, but they're salted using a static string, which is a well-known insecurity. This patch fixes that. I won't go into the details of why the existing mechanism is insecure; there is plenty of information available on that subject.

The hashes produced in this patch are compatible with several other modern frameworks, such as Django.

This patch also adds a layer of future-proofing to the auth module. Future hashing changes need not break existing stored hashes; since the hash algorithm is stored with the hash value, old hashes can be detected and dealt with appropriately. And it's trivially easy to add additional hash algorithms. 

To be compatible with the new auth module, auth drivers need to only make one small modification: In the _login function, instead of testing for equality between the provided password hash with the stored hash, these drivers need to call the new `check_hash()` function.

For example, the relevant change in the orm auth driver would look like this:

```
if ($this->check_hash($password,$user->password))
```

Finally, some of the auth driver boilerplate code in the Auth_File class was moved into Auth, which provides some reasonable default implementations for some of the less interesting functions. The only function now that a driver _needs_ to implement is the `password($user)` function, to retrieve the stored hash for a given user. Nonetheless, a driver certainly _can_ still re-implement other functions if they have some functionality to add.

The new storage format looks like this:

```
$sha1$NeCD5xCT$d355331f0c9e6251c2ab808c826a03c4b79220ec
```

The `$` signs act as delimiters.  In this case, `sha1` is the hashing algorithm, `NeCD5xCT` is the random salt, and `d355331f0c9e6251c2ab808c826a03c4b79220ec` is the resultant sha1 hash. If two users have the same password, the hash will be different because the salt will be different. This is an important security consideration.

Once this patch is accepted, I'll write the appropriate guide documentation.

### CODE REVIEW

**Comment by tylerl** [comment]
Redmine issue for this patch: http://dev.kohanaframework.org/issues/3792

**Comment by shadowhand** [comment]
So you reimplemented [Bonafide](https://github.com/shadowhand/bonafide) in Auth? Why?

**Comment by tylerl** [comment]
@shadowhand -- No, not quite. Bonafide is a completely new and separate authentication library. The goal wasn't to write a new one, but rather to fix the default library. The default Auth library shipped with Kohana should be secure and simple without requiring unnecessary third-party extensions. More esoteric options such as PBKDF2 are trivially easy to add, but the focus here is on compatibility and security.

**Comment by shadowhand** [comment]
>  The default Auth library shipped with Kohana should be secure and simple without requiring unnecessary third-party extensions.

I completely agree, but you are reinventing the wheel. The goal should be to integrate Bonafide with Auth, not to duplicate Bonafide in Auth. Besides, this patch has no flexibility to add additional hashing methods without editing the class itself, which is less than desirable.

**Comment by tylerl** [comment]
So just so that we're on the same page:

You have a patch in front of you which fixes some significant security problems with the code you're currently shipping, and it would take no more effort on your part to integrate other than to hit "accept". 

But you'd prefer instead to leave it broken because you wrote a separate module that serves the same purpose, which you hope someday to use to replace the existing broken one... even though it's a different API and will break users' custom Auth modules and require a lot of work on everyone's part to integrate. 

Even if you prefer to replace Auth with Bonafide, I don't see why Auth can't be allowed to be fixed in the mean time.

I must say, every time I try to contribute something to this project, I'm met with the strangest and most irrational sort of resistance.

**Pull request closed without merging**
